services:
  front:
    image: front
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DOWNLOAD_PATH=public/downloads/vsix
    volumes:
      - /home/pedrocamargo/vsix:/app/${DOWNLOAD_PATH} # Monta o volume /vsix no container para baixar os arquivos .vsix
